### ISSUE TITLE
Publishing to Maven

### ISSUE THREAD

**Issue by ScottPeterJohnson** [emotionbug/jdbc-sshj#6]
I noticed you'd taken steps to update this library and publish it to Maven, which is great because I also needed it there. But it doesn't seem to be published yet, so I was wondering if you could use any help with e.g. configurations, as the Sonatype process can be a bit confusing and I've done it before.

**Comment by emotionbug** [comment]
@ScottPeterJohnson 
thanks for your attention. today, finally I published on sonatype. and It will be able to search on Maven repo after 2 hours.

https://s01.oss.sonatype.org/content/groups/public/io/github/emotionbug/jdbc-sshj/

**Comment by ScottPeterJohnson** [comment]
Great work! :tada:
